### ISSUE TITLE
Let users see details of existing sources

### ISSUE THREAD

**Issue by mikumino** [mikumino/nijika#5]
Users can create sources and log them but not much else beyond that. Total duration is something that is stored (it probably doesn't need to be) as well as a source's description and type. A command that allows users to see these details would be nice, as users could see how much time they've spent on any source as well as review its other information in the case they want to edit it.

**Comment by mikumino** [comment]
This will likely use autocompletion. It would be better to complete https://github.com/mikumino/nijika/issues/3 before this one.

**Comment by colbydeason** [comment]
sourceview created
